services:
  - type: web
    name: image-search-api
    env: node
    buildCommand: "npm install && npm run build && ls -la dist/"
    startCommand: "npm start"
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SEARCH_ENGINE_ID
        sync: false
